### ISSUE TITLE
Field "domain" is missing from getAllHosts()

### ISSUE THREAD

**Issue by marklikeapenny** [EvernodeXRPL/evernode-js-client#173]
It's about `registryClient.getAllHosts();` vs `registryClient.getActiveHosts();`.

The returned Json from `getAllHosts()` is missing the `domain` field.

**Comment by chalith** [comment]
Did you try in 'evernode-js-client' latest version?

**Comment by marklikeapenny** [comment]
You're right. The project was not up to date anymore. It's working fine now. Thank you!
