### ISSUE TITLE
Error: Both address and secret cannot be empty - Registry Client

### ISSUE THREAD

**Issue by dangell7** [EvernodeXRPL/evernode-js-client#195]
The following throws an error when trying to create a registry client.

```
const client = new evernode.RegistryClient({
      registryAddress: "rmv53yu8Wid6kj6AC6NvmiwSXNxRa8vTH",
      rippledServer: "wss://xahau.network",
});
await client.connect();
```

Am I constructing this wrong? Is the documentation up to date?

```fullExample.js
async function getHosts() {
  try {
    const tenantAddress = process.env.EV_TENANT_ADDRESS;
    const tenantSecret = process.env.EV_TENANT_SECRET;
    const client = new evernode.RegistryClient({
      registryAddress: "rmv53yu8Wid6kj6AC6NvmiwSXNxRa8vTH",
      rippledServer: "wss://xahau.network",
    });
    await client.connect();
    const activeHosts = await client.getActiveHosts();
    console.log(activeHosts);
    await client.disconnect();
  } catch (error) {
    console.log(error);
  }
}
getHosts();
```

**Comment by gadget78** [comment]
we figured it out in discord, for others needing help... 
need to setup the "defaults", and use the HookClientFactory.
and use the functions that use the ledger, and not the API/firestore

'''const evernode = require('evernode-js-client');

async function getHosts() {
  try {
	evernode.Defaults.set( {
		governorAddress: "rBvKgF3jSZWdJcwSsmoJspoXLLDVLDp6jg",
		rippledServer: "wss://xahau.network"
	} );
	const registryClient = await evernode.HookClientFactory.create('REGISTRY');
        const status = await registryClient.connect();
        console.log(status);
	console.log(registryClient);

	const activeHosts = await registryClient.getActiveHostsFromLedger();
	console.log(activeHosts);
	} catch (error) {
    console.log(error);
  }
}

getHosts();
''''
