### ISSUE TITLE
How to `acquireLease` without a contract id.

### ISSUE THREAD

**Issue by dangell7** [EvernodeXRPL/evernode-js-client#196]
In the documentation it says to do:

```
const timeout = 10000;
const result = await tenant.acquireLease(
  hostAddress,
  {
    owner_pubkey:
      "ed5cb83404120ac759609819591ef839b7d222c84f1f08b3012f490586159d2b50",
    contract_id: "dc411912-bcdd-4f73-af43-32ec45844b9a",
    image: "evernodedev/sashimono:hp.latest-ubt.20.04-njs.20",
    config: {},
  },
  { timeout: timeout }
);
```

How do I know or get the `owner_pubkey` and `contract_id`?

I have a contract, I've built the min, now I need to acquire leases and deploy the contract

**Comment by kithminisg** [comment]
@dangell7 ,
`owner_pubkey`: You can generate a sign key pair and provide the public key (Key type is ed25519, Key encoding is HEX). You need to add an `ed` prefix as an identification of the key type.
`contract_id`: You can generate a UUID and provide that.
